
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-09
owner: ucsb-cs156-s26
repo_name: team02-s26-09
pull_requests: [{"author":{"id":"MDQ6VXNlcjY2MzMzMjQ0","is_bot":false,"login":"CooperDalton","name":"Cooper Dalton"},"headRefName":"codex/issue-32-menu-item-review-table","number":70,"title":"Add MenuItemReview table component","url":"https://github.com/ucsb-cs156-s26/team02-s26-09/pull/70"},{"author":{"id":"MDQ6VXNlcjY2MzMzMjQ0","is_bot":false,"login":"CooperDalton","name":"Cooper Dalton"},"headRefName":"codex/issue-31-menu-item-review-form","number":69,"title":"Add MenuItemReview form component","url":"https://github.com/ucsb-cs156-s26/team02-s26-09/pull/69"},{"author":{"id":"MDQ6VXNlcjY2MzMzMjQ0","is_bot":false,"login":"CooperDalton","name":"Cooper Dalton"},"headRefName":"codex/issue-30-menu-item-review-fixtures","number":68,"title":"Add MenuItemReview fixtures","url":"https://github.com/ucsb-cs156-s26/team02-s26-09/pull/68"},{"author":{"id":"MDQ6VXNlcjM3NzUzNzYy","is_bot":false,"login":"RitxmSaha","name":"Ritam Saha"},"headRefName":"Ritam-HelpRequest-placeholders","number":67,"title":"rs - Add HelpRequest placeholder pages and navbar link","url":"https://github.com/ucsb-cs156-s26/team02-s26-09/pull/67"},{"author":{"id":"MDQ6VXNlcjY2MzMzMjQ0","is_bot":false,"login":"CooperDalton","name":"Cooper Dalton"},"headRefName":"Cooper-MenuItemReview-backend-copy","number":66,"title":"Menu Item Backend Copy","url":"https://github.com/ucsb-cs156-s26/team02-s26-09/pull/66"}]
